Added new setting to exclude user agents #19
matomo-org/plugin-TrackingSpamPrevention pull request #21
Opened 2021-08-24 07:59 UTC by AltamashShaikh

### Description:

Added new setting to exclude user agents 
Issue: #19

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

2021-08-25 15:28 UTC, sgiehl commented on lang/en.json
> +    "SettingExcludeServerSideLibrariesDescription": "Server Side Libraries Like %1$s are excluded.",
As you are displaying the full list of excluded libraries the `like` might be a bit misleading.

2021-08-25 20:56 UTC, tsteur commented
![image](https://user-images.githubusercontent.com/273120/130862902-944f6eb1-a4f1-4061-acb1-77ea4d920eaa.png)

@AltamashShaikh the list is quite long (and there are no spaces). Maybe we could just mention a few most popular examples.

Also could we move this setting up next to the other 3 checkboxes? 

For consistency could we name this setting something like `Block tracking requests from server side libraries`?

Then In the setting description we should explain to users when this can be disabled and when not similar to the other settings. Like we could say `When this feature is enabled it will block tracking requests made from server side libraries like .... If you are only tracking using our JavaScript tracker then you can safely enable these features as any request from such server side libraries would not be expected and indicates spam. If you are using a server side SDK like our PHP tracking SDK, Java SDK, Python SDK, Android or iOS SDK, or others to track data then you should not enable this feature`. Something like that.

2021-08-25 20:57 UTC, tsteur commented on TrackingSpamPrevention.php
> +        $deviceDetector = new DeviceDetector($request->getUserAgent());
@AltamashShaikh could you create the tracker instance similar to here https://github.com/matomo-org/matomo/blob/4.4.1/plugins/DevicesDetection/Columns/Base.php#L19 ?

Otherwise it won't use various caches and it will slow down tracking execution a lot.

Also for performance we would only want to create the tracker instance and only parse the user agent when the setting is enabled. Otherwise it can quickly make the tracking request 10-100% slower.

2021-08-25 20:59 UTC, tsteur commented on TrackingSpamPrevention.php
> +            $excluded = 'excluded: ServerSideLibraries-';
@AltamashShaikh can we add tests for this to `plugins/TrackingSpamPrevention/tests/Integration/TrackingSpamPreventionTest.php`? Similar to the other tests eg similar to `test_isExcludedVisit_whenBlockedUserAgent` and `test_isExcludedVisit_whenBlockedUserAgentWhenGoodUserAgentWontBlock` and `test_isExcludedVisit_whenBlockedUserAgentDisabled` etc?

2021-08-26 05:58 UTC, AltamashShaikh commented on lang/en.json
> +    "SettingExcludeServerSideLibrariesDescription": "Server Side Libraries Like %1$s are excluded.",
Changed the description text

2021-08-26 05:59 UTC, AltamashShaikh commented
> ![image](https://user-images.githubusercontent.com/273120/130862902-944f6eb1-a4f1-4061-acb1-77ea4d920eaa.png)
> 
> @AltamashShaikh the list is quite long (and there are no spaces). Maybe we could just mention a few most popular examples.
> 
> Also could we move this setting up next to the other 3 checkboxes?
> 
> For consistency could we name this setting something like `Block tracking requests from server side libraries`?
> 
> Then In the setting description we should explain to users when this can be disabled and when not similar to the other settings. Like we could say `When this feature is enabled it will block tracking requests made from server side libraries like .... If you are only tracking using our JavaScript tracker then you can safely enable these features as any request from such server side libraries would not be expected and indicates spam. If you are using a server side SDK like our PHP tracking SDK, Java SDK, Python SDK, Android or iOS SDK, or others to track data then you should not enable this feature`. Something like that.

Yes updated the text as discussed

2021-08-26 05:59 UTC, AltamashShaikh commented on TrackingSpamPrevention.php
> +        $deviceDetector = new DeviceDetector($request->getUserAgent());
@tsteur Added, please check if this looks good.

2021-08-26 06:01 UTC, AltamashShaikh commented on TrackingSpamPrevention.php
> +            $excluded = 'excluded: ServerSideLibraries-';
Added 4 new test cases
1. When the setting is disabled and non server side user agent
2. When the setting is disabled and server side user agent
3. When the setting is enabled and non server side user agent
4. When the setting is enabled and server side user agent

2021-08-26 21:25 UTC, tsteur requested changes
Nice @AltamashShaikh  that works 👍 

Left only a few minor comments.

There is one problem though. The screenshot test you added was not added through GIT LFS but it should. I'm now always getting git errors like these:

![image](https://user-images.githubusercontent.com/273120/131038145-da98d92f-f146-42b7-a74a-399c9c9969a3.png)


You can see on https://github.com/matomo-org/plugin-TrackingSpamPrevention/blob/4.x-dev/tests/UI/expected-screenshots/TrackingSpamPreventionSettings_page.png it shows 
![image](https://user-images.githubusercontent.com/273120/131038105-a74d233b-de26-4143-a223-69aa1136cfb6.png)


but for https://github.com/matomo-org/plugin-TrackingSpamPrevention/blob/19-setting-to-block-UAs/tests/UI/expected-screenshots/TrackingSpamPreventionSettings_page.png it doesn't.

Might need to remove the screenshot and then install git lfs: https://github.com/git-lfs/git-lfs/wiki/Installation and add it again

2021-08-26 21:25 UTC, tsteur commented on ServerSideLibraryDetection.php
> +    public function isLibrary($userAgent) {
not too important but we could move this method into `BrowserDetection` class next to `isHeadlessBrowser`.

Could we maybe also add just a few basic tests for this method just to make sure it works?

2021-08-26 21:25 UTC, tsteur commented on SystemSettings.php
> +    public $blockeServerSideLibraries;
There's a minor typo `blocke` which should be `block`

2021-08-26 21:25 UTC, tsteur commented on lang/en.json
> +    "SettingBlockServerSideLibrariesTitle": "Block tracking requests from Server Side Libraries",
let's maybe use lower case for `Block tracking requests from server side libraries`

2021-08-27 05:00 UTC, AltamashShaikh commented on ServerSideLibraryDetection.php
> +    public function isLibrary($userAgent) {
Yes moved to BrowserDetection and added testcases

2021-08-27 05:00 UTC, AltamashShaikh commented on lang/en.json
> +    "SettingBlockServerSideLibrariesTitle": "Block tracking requests from Server Side Libraries",
Changed to lowercase

2021-08-27 05:01 UTC, AltamashShaikh commented on SystemSettings.php
> +    public $blockeServerSideLibraries;
Typo fixes

2021-08-27 05:01 UTC, AltamashShaikh commented
> Nice @AltamashShaikh that works 
> 
> Left only a few minor comments.
> 
> There is one problem though. The screenshot test you added was not added through GIT LFS but it should. I'm now always getting git errors like these:
> 
> ![image](https://user-images.githubusercontent.com/273120/131038145-da98d92f-f146-42b7-a74a-399c9c9969a3.png)
> 
> You can see on https://github.com/matomo-org/plugin-TrackingSpamPrevention/blob/4.x-dev/tests/UI/expected-screenshots/TrackingSpamPreventionSettings_page.png it shows
> ![image](https://user-images.githubusercontent.com/273120/131038105-a74d233b-de26-4143-a223-69aa1136cfb6.png)
> 
> but for https://github.com/matomo-org/plugin-TrackingSpamPrevention/blob/19-setting-to-block-UAs/tests/UI/expected-screenshots/TrackingSpamPreventionSettings_page.png it doesn't.
> 
> Might need to remove the screenshot and then install git lfs: https://github.com/git-lfs/git-lfs/wiki/Installation and add it again

Thanks, Updated via git lfs

2021-08-30 00:56 UTC, tsteur commented
Nice 🎉  Let's maybe have a look later how to release a new version

2021-08-30 00:57 UTC, merged