Changed to PHP from twig for ban ip email template
matomo-org/plugin-TrackingSpamPrevention pull request #37
Opened 2021-12-02 04:42 UTC by AltamashShaikh

### Description:

Changed to PHP from twig for ban ip email template.
Fixes: #32

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

2021-12-02 04:44 UTC, AltamashShaikh commented on BanIpNotificationEmail.php
> +        $mail->setBodyHtml(Common::sanitizeInputValue($mailBody));
@tsteur 
This works but due Common::sanitizeInputValue the email body is not rendering properly.

2021-12-02 09:58 UTC, Findus23 commented on BanIpNotificationEmail.php
> +        $mail->setBodyHtml(Common::sanitizeInputValue($mailBody));
The solution would be not to sanitize the full HTML, but every variable you plug into the HTML, right?

2021-12-02 09:58 UTC, Findus23 commented on BanIpNotificationEmail.php
> +        $mailBody = 'This is for your information. The following IP was banned because visit tried to track more than '.$maxActionsAllowed.' actions:';
It would be really great if you could make all texts translatable.

2021-12-02 19:15 UTC, tsteur commented on BanIpNotificationEmail.php
> +        $mailBody = 'This is for your information. The following IP was banned because visit tried to track more than '.$maxActionsAllowed.' actions:';
I'm not sure if we actually have translations in tracker, possible we do. If we have translations, then could make it translatable

2021-12-03 03:29 UTC, AltamashShaikh commented on BanIpNotificationEmail.php
> +        $mailBody = 'This is for your information. The following IP was banned because visit tried to track more than '.$maxActionsAllowed.' actions:';
@Findus23 @tsteur 
Translation is not working, I have removed it from subject too.

Also santizing only the variable seems to work properly

2021-12-03 04:17 UTC, AltamashShaikh commented on tests/Integration/NotificationEmailTest.php
> -Current date (UTC): 2020-12-14 01:42:27
@tsteur 
This is not being returned currently due to
`SettingsPiwik::getPiwikInstanceId()` is returning `false`

Did I miss anything here ?

2021-12-03 09:35 UTC, Findus23 commented on BanIpNotificationEmail.php
> +        $mailBody = 'This is for your information. The following IP was banned because visit tried to track more than '.$maxActionsAllowed.' actions:';
Ah, that's a pity as unlike other tracker errors its an user-facing text, but it makes sense that we can't easily translate it.

2021-12-07 01:23 UTC, tsteur requested changes
@AltamashShaikh mentioned a few issues as a comment. Also the email is now HTML vs before it was text. Can we change this back again?

2021-12-07 01:23 UTC, tsteur commented on BanIpNotificationEmail.php
> +                        <br> IP as detected in header: ' . Common::sanitizeInputValue(\Piwik\IP::getIpFromHeader()) . '
@AltamashShaikh all this should still be there when an instanceId is set. It's only the first line that we don't need to show when instanceId is not set. This line seems to have actually gone? I'm meaning `{% if instanceId is not empty %}Instance ID: {{ instanceId }}{% endif %}`

![image](https://user-images.githubusercontent.com/273120/144948328-68a65779-b801-40c6-922c-70359406fd59.png)

2021-12-07 01:23 UTC, tsteur commented on BanIpNotificationEmail.php
> +                        <br> IP as detected in header: ' . Common::sanitizeInputValue(\Piwik\IP::getIpFromHeader()) . '
Also the IP we already have as a variable above and shouldn't use `\Piwik\IP::getIpFromHeader()`

2021-12-07 03:45 UTC, AltamashShaikh commented on BanIpNotificationEmail.php
> +                        <br> IP as detected in header: ' . Common::sanitizeInputValue(\Piwik\IP::getIpFromHeader()) . '
@tsteur 
Fixed and reverted back to setBodyText

2021-12-07 20:53 UTC, tsteur requested changes
One last change @AltamashShaikh  and we should be also removing the no longer needed twig file.

2021-12-07 20:53 UTC, tsteur commented on BanIpNotificationEmail.php
> +IP as detected in header: ' . Common::sanitizeInputValue($ip) . '
@AltamashShaikh sorry just seeing we used to use `\Piwik\IP::getIpFromHeader();` there before. Bit confusing we're reporting two different IPs. Let's maybe change it back to `\Piwik\IP::getIpFromHeader();` for now. Then we should be good to merge.

2021-12-07 20:53 UTC, tsteur commented on BanIpNotificationEmail.php
> +GET request info: ' . json_encode($get, JSON_HEX_APOS) . '
Out of curiousity: Any particular reason we are using `JSON_HEX_APOS` option here?

2021-12-08 02:50 UTC, AltamashShaikh commented on BanIpNotificationEmail.php
> +GET request info: ' . json_encode($get, JSON_HEX_APOS) . '
Just to resolve any encoding issues since it has $_GET and $_POST

2021-12-08 02:55 UTC, AltamashShaikh commented on BanIpNotificationEmail.php
> +IP as detected in header: ' . Common::sanitizeInputValue($ip) . '
Reverted back

2021-12-08 03:42 UTC, AltamashShaikh commented on BanIpNotificationEmail.php
> +GET request info: ' . json_encode($get, JSON_HEX_APOS) . '
I have removed `JSON_HEX_APOS`

2021-12-08 03:59 UTC, tsteur approved these changes
feel free to merge if tests pass 👍 

since we're having a problem with this on cloud production might be good to trigger a release after merging already.

2021-12-08 04:24 UTC, merged