Improving Azure URL parsing
matomo-org/plugin-TrackingSpamPrevention pull request #91
Opened 2023-02-15 03:40 UTC by snake14

### Description:

The builds were failing indicating that the Azure page has changed again breaking our URL parsing. This PR is to address that.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

2023-02-15 04:32 UTC, snake14 commented
@sgiehl The last failing build (PHP 8.1 and minimum Matomo) appears to be related to DeviceDetector. Any recommendations on getting it to pass?

2023-02-15 04:35 UTC, AltamashShaikh commented on BlockedIpRanges/Azure.php
> +        if (stripos($contentDownloadPageSubstr, 'https') === false) {
@snake14 Any reason for this check?

2023-02-15 08:29 UTC, sgiehl commented
The minimum required version is currently Matomo 4.0.5. That one uses a version of device detector (4.0.2), that was not fully compatible with PHP 8.1
I guess there isn't much we can do about that failing tests. We could explicitly skip them on PHP 8.1 or higher if Matomo version is lower than 4.7.

2023-02-15 19:50 UTC, snake14 commented on BlockedIpRanges/Azure.php
> +        if (stripos($contentDownloadPageSubstr, 'https') === false) {
Yes. A few weeks ago, I [adjusted the length](https://github.com/matomo-org/plugin-TrackingSpamPrevention/commit/c25af48f85df37157d3716fde811a446537ea410) to fix an invalid URL. This changes back, but has a second check to account for if the same thing from a few weeks ago happens again. I figured this would make the parsing less brittle.

2023-02-15 19:51 UTC, snake14 commented
> The minimum required version is currently Matomo 4.0.5. That one uses a version of device detector (4.0.2), that was not fully compatible with PHP 8.1 I guess there isn't much we can do about that failing tests. We could explicitly skip them on PHP 8.1 or higher if Matomo version is lower than 4.7.

Thank you @sgiehl . I'll try checking the versions and skipping if necessary.

2023-02-16 00:46 UTC, snake14 commented on BlockedIpRanges/Azure.php
> +        if (stripos($contentDownloadPageSubstr, 'https') === false) {
I just added some more asserts to one of the tests to catch issues with the download link earlier.

2023-02-16 02:15 UTC, AltamashShaikh commented on BlockedIpRanges/Azure.php
> +        if (stripos($contentDownloadPageSubstr, 'https') === false) {
can you add a comment for the same in the code?

2023-02-16 02:16 UTC, AltamashShaikh requested changes
@snake14 Just requested 1 change to add comment in the code, so that we/anyone editing the code have clear idea why we have this

2023-02-16 02:32 UTC, AltamashShaikh approved these changes

2023-02-16 02:33 UTC, AltamashShaikh commented
@snake14 Also good to release a new version of the plugin

2023-02-16 02:34 UTC, snake14 commented on BlockedIpRanges/Azure.php
> +        if (stripos($contentDownloadPageSubstr, 'https') === false) {
Done

2023-02-16 02:45 UTC, snake14 commented
Thank you @AltamashShaikh . I actually just realised why the position was so variable. The code was using `strpos` instead of `mb_strpos` while dealing with a UTF-8 encoded page. I just made that correction and removed the if statement as it shouldn't be necessary anymore.

2023-02-16 02:50 UTC, AltamashShaikh commented on BlockedIpRanges/Azure.php
> +        $posStart = mb_strpos($contentDownloadPage, $prefixUrl . 'https://download.microsoft.com/download/');
unlike below line don't we need to specify the encoding as `UTF-8` ?

2023-02-16 02:54 UTC, snake14 commented on BlockedIpRanges/Azure.php
> +        $posStart = mb_strpos($contentDownloadPage, $prefixUrl . 'https://download.microsoft.com/download/');
Thank you for catching that. It worked without specifying, but it would be safer to do so.

2023-02-16 03:00 UTC, AltamashShaikh approved these changes

2023-02-16 03:06 UTC, merged